/**
 * MODULE 4: title block, locked-dimension table, room schedule, legend and
 * the printed proof of every dimension chain (taken from validate.js).
 */
const G = require('../geometry')
const D = require('../draw')
const { fmt, ft } = require('../units')
const { validate } = require('../validate')

const { C } = D

const sqft = (r) => ((r.x2 - r.x1) * (r.y2 - r.y1)) / 144

const roomSchedule = () => {
    const by = Object.fromEntries(G.rooms.map((r) => [r.id, r]))
    const row = (name, rects, size) => [name, size, `${rects.reduce((a, r) => a + sqft(by[r]), 0).toFixed(0)} sq ft`]
    const sz = (r) => `${fmt(by[r].x2 - by[r].x1)} x ${fmt(by[r].y2 - by[r].y1)}`
    return [
        row('Shops 1-4 (each)', ['shop1'], `${fmt(G.SHOP_FRONT)} x ${fmt(160)}`),
        row('Car porch', ['porch'], sz('porch')),
        row('Lounge / dining', ['lounge', 'loungeBay'], `${sz('lounge')} + bay`),
        row('Kitchen', ['kitchen'], sz('kitchen')),
        row('Master bed', ['master', 'masterRear'], `${fmt(by.master.x2 - by.master.x1)} x ${fmt(G.keys.YT - by.master.y1)}*`),
        row('Bedroom 2', ['bed2'], sz('bed2')),
        row('Master bath', ['mbath'], sz('mbath')),
        row('Bath 2', ['bath2'], sz('bath2')),
        row('Stair (17 x 9½")', ['stair'], sz('stair')),
        row('Open shaft', ['shaft'], sz('shaft')),
    ]
}

const renderPanel = (w, h) => {
    const img = D.blank(w, h)
    D.strokeRect(img, 2, 2, w - 3, h - 3, C.ink, 3)
    let y = 50
    const left = 36
    const T = (s, size, color = C.ink, x = left) => D.textLeft(img, s, x, y, size, color)
    T('GROUND FLOOR PLAN', 52); y += 58
    T(`Plot ${fmt(G.PLOT_W)} x ${fmt(G.PLOT_H)}  -  4 shops + residence`, 30, C.grey); y += 34
    T('All dimensions computed and verified in code', 26, C.dim); y += 30
    T('(plot -> wall-to-wall -> clear room)', 26, C.dim); y += 54

    const table = (title, rows, cols) => {
        T(title, 32); y += 16
        D.line(img, left, y, w - left, y, C.ink, 2); y += 28
        for (const r of rows) {
            r.forEach((cell, i) => D.textLeft(img, cell, left + cols[i], y, 23, i === 0 ? C.ink : C.dim))
            y += 32
        }
        y += 30
    }

    table('LOCKED DIMENSIONS', [
        ['Plot', `${fmt(G.PLOT_W)} x ${fmt(G.PLOT_H)}`],
        ['Commercial road (left)', fmt(G.PLOT_H)],
        ['Residential road (bottom)', fmt(G.PLOT_W)],
        ['Shops', '4'],
        ['Shop frontage (clear, each)', fmt(G.SHOP_FRONT)],
        ['Total clear shop frontage', fmt(4 * G.SHOP_FRONT)],
        ['Shop clear depth', fmt(160)],
        ['Commercial band gross', `${fmt(187)}  (= 41'-8" - 26'-1")`],
        ['Residence gross', `${fmt(317)}  (= 42'-0" - 15'-7")`],
        ['Residence clear (inside walls)', `${fmt(G.keys.XR - G.keys.X0)} x ${fmt(G.keys.YT - G.keys.Y0)}`],
        ['External / boundary walls', fmt(G.EXT)],
        ['Internal partitions', fmt(G.PART)],
        ['House entrance / car gate', 'bottom road, gate at right'],
    ], [0, 440])

    table('ROOM SCHEDULE (clear)', roomSchedule(), [0, 330, 700])
    D.textLeft(img, '* master is L-shaped: 3\'-10" x 4\'-4½" corner given to the shaft', left, y - 30, 20, C.grey)
    y += 30

    T('LEGEND', 32); y += 16
    D.line(img, left, y, w - left, y, C.ink, 2); y += 40
    const sw = (draw, label) => {
        draw(left, y - 16, left + 90, y + 16)
        D.textLeft(img, label, left + 120, y, 23)
        y += 50
    }
    sw((a, b, c, d) => D.fillRect(img, a, b + 7, c, d - 7, C.wall), `Wall: ${fmt(G.EXT)} external, ${fmt(G.PART)} partition`)
    sw((a, b, c, d) => {
        D.fillRect(img, a, b + 7, c, d - 7, C.paper)
        for (const f of [0, 0.5, 1]) D.line(img, a, b + 7 + (d - b - 14) * f, c, b + 7 + (d - b - 14) * f, f === 0.5 ? C.glass : C.ink, 2)
    }, 'Window / ventilator')
    sw((a, b, c, d) => { D.line(img, a, d, a, b - 40, C.ink, 3); D.arc(img, a, d, 56, -Math.PI / 2, 0, C.grey, 2) }, 'Door with swing')
    sw((a, b, c, d) => { D.line(img, a, (b + d) / 2 - 4, c, (b + d) / 2 - 4, C.ink, 2, [10, 6]); D.line(img, a, (b + d) / 2 + 4, c, (b + d) / 2 + 4, C.ink, 2, [10, 6]) }, 'Rolling shutter (shop front)')
    sw((a, b, c, d) => D.line(img, a, (b + d) / 2, c, (b + d) / 2, C.ink, 3, [16, 8]), 'Car gate (in boundary line)')
    sw((a, b, c, d) => { D.fillRect(img, a, b, c, d, C.setback); D.hatch(img, a, b, c, d, C.light, 10) }, '9" front setback / step')
    return img
}

const renderProofs = (w) => {
    const { report, ok } = validate()
    const lines = report
    const h = 120 + lines.length * 34
    const img = D.blank(w, h)
    D.strokeRect(img, 2, 2, w - 3, h - 3, C.ink, 3)
    D.textLeft(img, `DIMENSION PROOF  (generated by validate.js - ${ok ? 'ALL CHECKS PASS' : 'FAILED'})`, 36, 50, 32, ok ? C.ink : C.dim)
    let y = 104
    for (const l of lines) {
        D.textLeft(img, l, 36, y, 21, l.startsWith('OK') ? C.ink : C.dim)
        y += 34
    }
    return img
}

module.exports = { renderPanel, renderProofs, ft }
